version: '3'

services:
 application:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes: ["./application:/opt/application"]
   environment:
     PORT: "5005"
     FLASK_DEBUG: "true"
   ports:
     - "5005:5005"
